# Creating a Docker container action https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# Metadata syntax for GitHub Actions https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: "Mirror Git"
branding:
  icon: "copy"
  color: "green"
author: "K8sCat <k8scat@gmail.com>"
description: "Synchronize git repositories like a mirror."
inputs:
  source_protocol:
    description: "https or ssh"
    require: true
    default: "https"
  source_host:
    description: "Git host without the protocol"
    required: true
    default: "github.com"
  source_port:
    description: "Git port"
    required: false
  source_username:
    description: "Username on source git server"
    required: true
  source_private_key:
    description: "SSH private key"
    required: false
  source_token:
    description: "Personal access token"
    required: false
  dest_protocol:
    description: "https or ssh"
    require: true
    default: "https"
  dest_host:
    description: "Git host without the protocol"
    required: true
    default: "github.com"
  dest_port:
    description: "Git port"
    required: false
  dest_username:
    description: "Username on dest git server"
    required: true
  dest_private_key:
    description: "SSH private key"
    required: false
  dest_token:
    description: "Personal access token"
    required: false
  dest_create_repo_script:
    description: "Script used to create repo on dest git server"
    required: false
  mirror_repos:
    description: "Repos to mirror, separated by comma"
    required: true
  push_tags:
    description: "Push tags via --mirror, true or false"
    required: false
    default: "true"
  skip_tags_repos:
    description: "Skip pushing tags for these repos, seperated by comma"
    required: false
  ignored_repos:
    description: "Ignore these repos, seperated by comma"
    required: false
  slack_webhook:
    description: "Slack webhook url"
    required: false
  dingtalk_webhook:
    description: "Dingtalk webhook url"
    required: false
  feishu_webhook:
    description: "Feishu webhook url"
    required: false
runs:
  using: "docker"
  image: "docker://gigrator/mirror-git:0.0.9"
