name: Example

on:
  workflow_dispatch:

jobs:
  mirror-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check tools
        run: |
          gh --version
          git --version

      - name: Login Source GitHub
        run: |
          echo "${{ secrets.SOURCE_TOKEN }}" > /tmp/.github_token
          gh auth login --with-token < /tmp/.github_token
          gh auth status
          rm -f /tmp/.github_token

      - name: List repos
        id: list_repos
        run: |
          gh repo list ${{ secrets.SOURCE_USERNAME }} -L 1000 > /tmp/repos.txt
          cat /tmp/repos.txt | while read -r repo; do
            repo_name=$(echo ${repo} | awk '{print $1}' | awk -F/ '{print $2}')
            if [[ -f "/tmp/repo_list.txt" ]]; then
              echo -n ",${repo_name}" >> /tmp/repo_list.txt
            else
              echo -n "${repo_name}" >> /tmp/repo_list.txt
            fi
          done
          repo_list=$(cat /tmp/repo_list.txt)
          echo "::set-output name=repo_list::${repo_list}"

      - name: action-git-mirror
        uses: k8scat/action-git-mirror@v0.0.28
        with:
          source_protocol: https
          source_host: github.com
          source_username: ${{ secrets.SOURCE_USERNAME }}
          source_token: ${{ secrets.SOURCE_TOKEN }}
          dest_protocol: ssh
          dest_host: github.com
          dest_username: ${{ secrets.DEST_USERNAME }}
          dest_private_key: ${{ secrets.DEST_PRIVATE_KEY }}
          push_tags: "true"
          mirror_repos: ${{ steps.list_repos.outputs.repo_list }}
          # repo3 and repo4 will only sync branches and commits
          skip_tags_repos: "repo3,repo4"
          # repo5 and repo6 will not be synced
          ignored_repos: "repo5,repo6"
          dest_create_repo_script: |
            # create repo via github cli
            if ! gh auth status; then
              token_file="/tmp/.github_token"
              echo "${INPUT_DEST_TOKEN}" > "${token_file}"
              gh auth login --with-token < "${token_file}"
              gh auth status
            fi

            repo="${INPUT_DEST_USERNAME}/${REPO_NAME}"
            found=$(gh repo list ${{ secrets.SOURCE_USERNAME }} -L 1000 | grep -i "${repo}")
            if [[ -z "${found}" ]]; then
              gh repo create "${INPUT_DEST_USERNAME}/${REPO_NAME}" --private
            fi
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          # dingtalk_webhook: ${{ secrets.DINGTALK_WEBHOOK }}
          # lark_webhook: ${{ secrets.LARK_WEBHOOK }}
          force_push: "true"
          dest_delete_repo_script: |
            # delete repo via github cli
            if ! gh auth status; then
              token_file="/tmp/.github_token"
              echo "${INPUT_DEST_TOKEN}" > "${token_file}"
              gh auth login --with-token < "${token_file}"
              gh auth status
            fi
            gh repo delete "${INPUT_DEST_USERNAME}/${REPO_NAME}" --confirm
