name: Mirror Git

on:
  workflow_dispatch:

jobs:
  mirror-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check tools
        run: |
          gh --version
          git --version

      - name: Login Source GitHub
        run: |
          source functions/gh
          gh_login "${{ secrets.SOURCE_TOKEN }}"
          gh auth status

      - name: List repos
        id: list_repos
        run: |
          gh repo list ${{ secrets.SOURCE_USERNAME }} -L 1000 > /tmp/repos.txt
          cat /tmp/repos.txt | while read -r repo; do
            repo_name=$(echo ${repo} | awk '{print $1}' | awk -F/ '{print $2}')
            if [[ -f "/tmp/repo_list.txt" ]]; then
              echo -n ",${repo_name}" >> /tmp/repo_list.txt
            else
              echo -n "${repo_name}" >> /tmp/repo_list.txt
            fi
          done
          repo_list=$(cat /tmp/repo_list.txt)
          echo "::set-output name=repo_list::${repo_list}"

      - name: action-git-mirror
        uses: k8scat/action-git-mirror@v0.0.8
        with:
          source_protocol: https
          source_host: github.com
          source_username: ${{ secrets.SOURCE_USERNAME }}
          source_token: ${{ secrets.SOURCE_TOKEN }}
          dest_protocol: ssh
          dest_host: github.com
          dest_username: ${{ secrets.DEST_USERNAME }}
          dest_private_key: ${{ secrets.DEST_PRIVATE_KEY }}
          push_tags: "true"
          mirror_repos: ${{ steps.list_repos.outputs.repo_list }}
          skip_tags_repos: "repo3,repo4"
          ignored_repos: "repo5,repo6"
          dest_create_repo_script: |
            # create repo via github cli
            echo "${DEST_TOKEN}" > ~/.github_token
            gh auth login --with-token < ~/.github_token
            gh auth status
            gh repo create "${DEST_USERNAME}/${REPO_NAME}" --private
            rm -f ~/.github_token
