name: GitHub to Gitee

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * 3"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login Source GitHub
        run: |
          gh --version
          echo "${{ secrets.SOURCE_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: List repos
        id: list_repos
        run: |
          repo_list=$(gh repo list -L 1000 --json name -t '{{range $i, $n := .}}{{if (gt $i 0)}},{{end}}{{$n.name}}{{end}}')
          echo "::set-output name=repo_list::${repo_list}"

      - name: GitHub to Gitee
        uses: k8scat/action-mirror-git@v0.1.2
        with:
          source_protocol: https
          source_host: github.com
          source_username: k8scat
          source_token: ${{ secrets.SOURCE_TOKEN }}
          dest_protocol: https
          dest_host: gitee.com
          dest_username: k8scat
          dest_token: ${{ secrets.DEST_TOKEN_GITEE }}
          mirror_repos: ${{ steps.list_repos.outputs.repo_list }}
          ignored_repos: ",Gigrator,"
          dest_create_repo_script: |
            curl \
              -H 'Content-Type: application/json;charset=UTF-8' \
              -d "{\"access_token\":\"${INPUT_DEST_TOKEN}\",\"name\":\"${REPO_NAME}\",\"private\":\"true\"}" \
              'https://gitee.com/api/v5/user/repos'
          lark_webhook: ${{ secrets.LARK_WEBHOOK }}
          notify_prefix: "GitHub to Gitee"
          ignore_error: "true"
